import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      link: {
          type: 'generated-index',
          title: 'Third Party Integrations',
          description: 'TODO',
          slug: '/integrations',
          keywords: ['guides'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'integrations'
        }
      ],
    },
  ]
}

export default sidebars;
